name: Check format

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'
      - 'liblouis/liblouis/liblouis.h.in'
  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'
      - 'liblouis/liblouis/liblouis.h.in'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  check-format:
    name: Check the code formatting

    runs-on: ubuntu-22.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y clang-format-14
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure
    - name: Check format
      run: |
        make format-sources
        git diff-index --exit-code HEAD -- .
